### ISSUE TITLE
program doesnt launch (latest version)

### ISSUE THREAD

**Issue by veezontyee** [ThereGoesMySanity/osuMissAnalyzer#12]
EDIT: No other versions work either, same issue listed below.

I've set both the directories specified in the options.cfg.

Every time I double click the exe or drop a file on the exe the blue wheel spins for a moment and then stops.

and then nothing happens. no error, program doesnt open, or anything. \
I've even tried running as administrator, or tried checking if the file was being blocked by my pc, but nothing seems wrong.

below is a gif of what happens.

https://gyazo.com/745c5c8837b70ba141fa7c7ef152cd0c

**Comment by ThereGoesMySanity** [comment]
i'm just stupid and forgot to add some of the dlls to the zip file... redownload it it works now

edit: I assume it works now, haven't tested it cause it's 6am and I need to go to sleep

**Comment by veezontyee** [comment]
All good, it's working now :D
