### ISSUE TITLE
Error when trying to analyse a replay with a big collection

### ISSUE THREAD

**Issue by Chiffario** [ThereGoesMySanity/osuMissAnalyzer#13]
With my map collection being over 80k maps, replay analyzer shows an error
![image](https://user-images.githubusercontent.com/49232762/95014489-f22ab400-064f-11eb-8149-0dfb26f40e63.png)
Translation: Index is out of the diapason. The index should be a positive number and its size shouldn't be bigger than the size of the collection. Option name: index

**Comment by ThereGoesMySanity** [comment]
There should be an exception.log file - can you send that to me or screenshot it?

**Comment by Chiffario** [comment]
[exception.log](https://github.com/ThereGoesMySanity/osuMissAnalyzer/files/5341360/exception.log)
I can change my system's language in a couple of hours if you need the thing to be in English

**Comment by ThereGoesMySanity** [comment]
Apparently, you have set a replay on a beatmap with 0 objects and that's what's causing it to crash. I don't think it has anything to do with your collection size.

**Comment by Chiffario** [comment]
I assumed it was a collection size issue because of how the error message was worded, my bad
However, I didn't set a replay on a map with 0 objects. I used a replay on Amakakeru Hoshi, ranked version an a ranked online play. If I choose a recent replay, it results in this appearing
![image](https://user-images.githubusercontent.com/49232762/95593279-26d4ac00-0a52-11eb-8ca8-f96939ef171b.png)
And if I use a manual beatmap search, it results in this
[exception.log](https://github.com/ThereGoesMySanity/osuMissAnalyzer/files/5355468/exception.log)

**Comment by CykaTV** [comment]
My collection is 92k large and Ive got the same issue... 

When I try to manually get a replay from my folder I get :
`System.Collections.Generic.KeyNotFoundException: La clé donnée était absente du dictionnaire.
   à System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   à OsuDbAPI.OsuDbFile.GetBeatmapFromHash(String mapHash)
   à OsuMissAnalyzer.UI.Options.GetBeatmapFromHash(String mapHash)
   à OsuMissAnalyzer.UI.UIReplayLoader.LoadBeatmap(Replay replay, Boolean dialog)
   à OsuMissAnalyzer.UI.UIReplayLoader.Load(String replayFile, String beatmapFile)
   à OsuMissAnalyzer.UI.Program.Main(String[] args)`

and when I try to take a recent, it crashes and I get :
`System.Collections.Generic.KeyNotFoundException: La clé donnée était absente du dictionnaire.
   à System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   à OsuDbAPI.OsuDbFile.GetBeatmapFromHash(String mapHash)
   à OsuMissAnalyzer.UI.Options.GetBeatmapFromHash(String mapHash)
   à OsuMissAnalyzer.UI.UIReplayLoader.LoadBeatmap(Replay replay, Boolean dialog)
   à OsuMissAnalyzer.UI.UIReplayLoader.<LoadReplay>b__18_4(Replay re)
   à System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   à System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   à System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   à OsuMissAnalyzer.UI.UIReplayLoader.LoadReplay()
   à OsuMissAnalyzer.UI.UIReplayLoader.Load(String replayFile, String beatmapFile)
   à OsuMissAnalyzer.UI.Program.Main(String[] args)`

**Comment by ThereGoesMySanity** [comment]
That looks like a different issue to me @CykaTV  - it seems like the program isn't able to find all of your maps in the osu!.db file.

Would you mind sending me your osu!.db file (_not_ osu!.\<user\>.db) so I could try to figure out if it's my program or your db file?

**Comment by ThereGoesMySanity** [comment]
@S1n1st3rn3ss it seems like the program is looking for your beatmaps in the wrong place - is your SongsDir config option set correctly?

**Comment by CykaTV** [comment]
Here you go
[osu!db.zip](https://github.com/ThereGoesMySanity/osuMissAnalyzer/files/5406756/osu.db.zip)

**Comment by ThereGoesMySanity** [comment]
@CykaTV Good news: the program is parsing your db file perfectly. Bad news: now I don't know what's wrong lol

The program is crashing because it can't find the beatmap in osu!.db - is it possible that you don't have the map for the replay you're trying to analyze? Does it crash for all replays or just some? If only some, can you send one that it does crash for?

**Comment by CykaTV** [comment]
ok i understand now : recently I have moved a lot my hard disk, and 1 month ago I lost 20k beatmaps. I think that corrupted my game by some way and now, when I add specifics maps, they disappear when I reboot. The fact is that I had redownloaded this map this morning (Tsukinami Nostalgia) but the game might be just corrupted, or at least the memory allocated to it...

**Comment by ThereGoesMySanity** [comment]
It's probably gonna take absolutely forever just cause of how many maps you have, but I think the only way to fix that would be to do a full reprocess of all your maps (F5 on song select).

**Comment by CykaTV** [comment]
Yeah I know, when I added 200GB worth of map it took me like 3 hours to proccess the whole thing

**Comment by ThereGoesMySanity** [comment]
@S1n1st3rn3ss are you still having this issue? I want to resolve this before I put out a new release

**Comment by ThereGoesMySanity** [comment]
Great - thanks!
