### ISSUE TITLE
Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by Halozhan** [ThereGoesMySanity/osuMissAnalyzer#16]
![image](https://user-images.githubusercontent.com/25768818/103293147-a4490080-4a32-11eb-944e-93d11d4e3d55.png)

in exception.log
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at OsuMissAnalyzer.Core.ScoresDb.ReadBeatmap()
   at OsuMissAnalyzer.Core.ScoresDb..ctor(String file)
   at OsuMissAnalyzer.UI.Options.AddOption(String key, String value)
   at OsuMissAnalyzer.UI.Options..ctor(String file, Dictionary`2 optList)
   at OsuMissAnalyzer.UI.Program.Main(String[] args)

**Comment by ThereGoesMySanity** [comment]
How large are your osu.db and scores.db?

**Comment by STCapricorn** [comment]
i have the same problem. my osu.db and scores.db are 35 MB and 767 KB respectively.

**Comment by ThereGoesMySanity** [comment]
Same exact error message? @STCapricorn

Uploading your scores.db would help me figure it out - on my computer the missanalyzer doesn't use nearly enough memory to cause an outofmemoryexcpetion, I'm assuming something weird is happening when scores.db is being read.

**Comment by STCapricorn** [comment]
yep, exact same. 
[exception.log](https://github.com/ThereGoesMySanity/osuMissAnalyzer/files/5785247/exception.log)

[scores.zip](https://github.com/ThereGoesMySanity/osuMissAnalyzer/files/5785249/scores.zip)
here's the scores.db; hope it helps

making osu regenerate the scores.db fixed it, fwiw.

**Comment by ThereGoesMySanity** [comment]
Fixed in v1.3.

@STCapricorn big thanks for sending your scores.db - I literally wouldn't have been able to figure this out without it 😳
