### ISSUE TITLE
"Incorrect syntax for filename, directory or hard drive"

### ISSUE THREAD

**Issue by balo22** [ThereGoesMySanity/osuMissAnalyzer#19]
https://i.gyazo.com/ee9a791781e9b0f6ad3e89e75e527219.png

Ive tried with and without including the song directory in the options, I haven't tried including an API key though because I didn't really understand where to get it or if I even need one. I have tried both dragging and droppong the replay on the exe as well opening the exe and selecting the replay that way.

thanks!

**Comment by rneacy** [comment]
remove the leading space.
it should be `osuDir=<filepath>`

**Comment by ThereGoesMySanity** [comment]
oh, yup ^ that would probably be it. Sorry, totally missed this!
