### ISSUE TITLE
changing server prefix in servers you're not in/ arent admin in externally in other servers

### ISSUE THREAD

**Issue by Arlind-dev** [ThereGoesMySanity/osuMissAnalyzer#20]
you can do >miss settings (server id you're not admin in) set prefix (whatever)
in a server where you are admin in to change some random server prefix where you arent admin

**Comment by ThereGoesMySanity** [comment]
ok that's very not good lol - this might actually be a bug in the discord api library i'm using

**Comment by ThereGoesMySanity** [comment]
nvm it was my bug - fixed.
