### ISSUE TITLE
Bot found a miss where there is no miss/sliderbreak?

### ISSUE THREAD

**Issue by praeludiumOrbis** [ThereGoesMySanity/osuMissAnalyzer#29]
https://discord.com/channels/288106529427554305/302224348352348160/927229380147695646 (https://discord.gg/bWV5vqw)
![image](https://user-images.githubusercontent.com/28674643/147881537-5650d8bb-3274-4c34-aab4-3e7baed233f2.png)
https://osu.ppy.sh/scores/osu/4012554317

**Comment by ThereGoesMySanity** [comment]
Fixed in 1.5
