### ISSUE TITLE
Program crashes if it encounters an empty file while searching for beatmap

### ISSUE THREAD

**Issue by Equbuxu** [ThereGoesMySanity/osuMissAnalyzer#3]
For some reason, I have several empty .osu files in osu/Songs which cause miss analyzer to crash

**Comment by Equbuxu** [comment]
The issue seems to be caused by this code:
MissAnalyzer.cs, readFolder()
```
string line = f.ReadLine();
...
if (line.StartsWith("BeatmapID"))
{
	if (line.Substring(10) == id)
	{
		return new Beatmap(file);
	}
}
```
If the file is empty, ReadLine() will returns null, which than causes exception when line.StartWith() is called.

**Comment by ThereGoesMySanity** [comment]
Merged your commit - thanks!
