### ISSUE TITLE
Bot shows every object after fail as miss in failed replays

### ISSUE THREAD

**Issue by praeludiumOrbis** [ThereGoesMySanity/osuMissAnalyzer#31]
(https://discord.com/channels/288106529427554305/313130987548835843/984897709515345990)

![image](https://user-images.githubusercontent.com/28674643/173134636-473e4dc8-e367-4374-9d87-752ea4eb8d94.png)

Replay: https://cdn.discordapp.com/attachments/313130987548835843/984897707795677214/MyAngelAku_-_kakichoco_-_Zanei_Illusion_2022-06-09_Osu.osr

**Comment by ThereGoesMySanity** [comment]
Fixed in 1.5
