### ISSUE TITLE
Application appears as a blank white box after selecting a replay

### ISSUE THREAD

**Issue by NatL7499** [ThereGoesMySanity/osuMissAnalyzer#36]
The message box for recent play selection appears and I can select a replay, but the application itself is blank.

![Screenshot 2022-07-12 183630](https://user-images.githubusercontent.com/71233101/178616007-c49b6fc0-c999-4684-815d-0ab3015ad246.png)

**Comment by ThereGoesMySanity** [comment]
Should be fixed now.
