### ISSUE TITLE
Mistakenly recognizes clicks as hits instead of misses

### ISSUE THREAD

**Issue by Piotrekol** [ThereGoesMySanity/osuMissAnalyzer#37]
Doesn't detect notelocked misses, as misses.
map: https://osu.ppy.sh/beatmapsets/859515#osu/2082006
[replay.zip](https://github.com/ThereGoesMySanity/osuMissAnalyzer/files/9192741/replay.zip) - failed at 0:38 by missclicking, then notelocking
analyzer - detects only single miss, second one is at replay boundary:
![image](https://user-images.githubusercontent.com/4990365/181096371-5fcb047a-65d9-4bef-ae1a-08271d27e2d8.png)

recording: 

https://user-images.githubusercontent.com/4990365/181097549-c1bbf24e-3e9c-45b5-b4d9-aaff9391fce9.mp4

__________

map: https://osu.ppy.sh/beatmapsets/1077335#osu/2409854
[replay2.zip](https://github.com/ThereGoesMySanity/osuMissAnalyzer/files/9213804/Piotrekol.-.EBIMAYO.-.GOODBOUNCE.NoBounce.2022-07-28.Osu.zip)
analyzer doesn't even detect misses - all 9 "detected" are outside of replay:
![image](https://user-images.githubusercontent.com/4990365/181627484-a9e955f1-236c-491d-9c72-d754e4317861.png)

**Comment by ThereGoesMySanity** [comment]
This was intentionally left as is, because I think the program is easier to use and understand like this

For a chain of notelock misses, the only "interesting" miss is the one that causes the notelock - I'd say it's actually more useful to know that you would've hit the rest if you hadn't notelocked in those cases.

If there are notelock misses in the second replay the analyzer should pick up at least one of them - that is probably a bug.

**Comment by ThereGoesMySanity** [comment]
Ok I opened the second replay in lazer and when I play it back there you also don't notelock lol - since I'm prioritizing accurate-to-lazer over accurate-to-stable going forward I'm going to close this.

**Comment by Piotrekol** [comment]
bummer - but understandable. Some context as to why I would want this fixed: main reason I'm reporting these is to eventually use hit reg present here in StreamCompanion, where I have access to live replay frames from stable.

**Comment by ThereGoesMySanity** [comment]
like a live updating MissAnalyzer window? or for something else?

I've wanted to have missanalyzer update live for a while now, I would be interested in helping if that were the case

**Comment by Piotrekol** [comment]
I can stream live replay frames over websocket or other means, so it could also mean live MissAnalyzer
