### ISSUE TITLE
The "Segoe UI" font family could not be found in the following directory: /usr/share/fonts/ (Linux)

### ISSUE THREAD

**Issue by verarr** [ThereGoesMySanity/osuMissAnalyzer#40]
I suspect I'm putting the fonts in the wrong directory (I tried installing them from the AUR).

OS: Arch Linux x86_64
osuMissAnalyzer: v1.6
exception.log: https://pastebin.com/hHVLWTBM

**Comment by farkasma** [comment]
Fix for me was putting the TTF files into /usr/local/share/fonts.
Also I'd say manual install is easier in this case, no AUR needed. You can just download the TTF files from anywhere on the web, Google is your friend.

**Comment by verarr** [comment]
I still can't get it to work.
Tried:
- `/usr/share/fonts/Segoe UI/*.ttf`
- `/usr/share/fonts/Segoe-UI/*.ttf`
- `/usr/share/fonts/*.ttf`
- `/usr/share/fonts/TTF/*.ttf`
- `/usr/local/share/fonts/*.ttf`
- `/usr/local/share/fonts/Segoe UI/*.ttf`
- `/usr/local/share/fonts/Segoe-UI/*.ttf`
- `/usr/local/share/fonts/TTF/*.ttf`
- `/home/*/.local/share/fonts/*.ttf`

It could be an issue with the name of the files themselves, so could you please describe exactly where you placed them?

Also, there isn't really a download link for a TTF of the font (you have to license it from Microsoft?)

**Comment by farkasma** [comment]
In /usr/local/share/fonts/Segoe UI/ there are 4 files:
- Segoe UI.ttf
- Segoe UI Italic.ttf
- Segoe UI Bold.ttf
- Segoe UI Bold Italic.ttf

This works for me.

Regarding the download, all I can tell you is that I got it from CufonFonts. [https://www.cufonfonts.com/font/segoe-ui-4](https://www.cufonfonts.com/font/segoe-ui-4)

**Comment by verarr** [comment]
It works, thank you!
