### ISSUE TITLE
BathBot compatibility

### ISSUE THREAD

**Issue by VectrorX** [ThereGoesMySanity/osuMissAnalyzer#42]
Hi, will you add compatibility with the Bathbot, its pretty widely used and it would be nice to have it working :)

**Comment by ThereGoesMySanity** [comment]
Bathbot compatibility already exists but doesn't work if you use slash commands unfortunately. I'll try to get something figured out for slash commands but it might be a while

**Comment by ThereGoesMySanity** [comment]
Slash command handling has been added, closing.
